name: Deploy Project 2 to ECS

on:
  push:
    branches:
      - branch2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-1

    - name: Build and Push Docker Image
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: us-west-1
      run: |
        IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/project2-app"
        
        # Build the Docker image
        docker build -t $IMAGE_URI ./myproject1
        
        # Tag the image with "latest"
        docker tag $IMAGE_URI $IMAGE_URI:latest

        # Push the Docker image to ECR
        docker push $IMAGE_URI:latest

    - name: Update ECS Service to Deploy New Task
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-1
      run: |
        # Update the ECS service to use the latest task definition
        aws ecs update-service \
          --cluster my-cluster \
          --service project2-service \
          --force-new-deployment \
          --region $AWS_REGION
