# name: Deploy Project 1 to ECS

# on:
#   push:
#     branches:
#       - branch1

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to Amazon ECR
#       uses: aws-actions/amazon-ecr-login@v1
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: us-west-1

#     - name: Build and Push Docker Image
#       env:
#         AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#         AWS_REGION: us-west-1
#       run: |
#         IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/project1-app"
        
#         # Build the Docker image
#         docker build --no-cache -t $IMAGE_URI ./myproject
        
#         # Tag the image with "latest"
#         docker tag $IMAGE_URI $IMAGE_URI:latest

#         # Push the Docker image to ECR
#         docker push $IMAGE_URI:latest

#     - name: Stop Existing ECS Tasks
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: us-west-1
#       run: |
#         # Fetch the currently running tasks for the task family
#         TASK_ARN_LIST=$(aws ecs list-tasks \
#           --cluster my-cluster \
#           --family my-task-def \
#           --region $AWS_REGION \
#           --query "taskArns" \
#           --output text)

#         # Stop all running tasks
#         for TASK_ARN in $TASK_ARN_LIST; do
#           echo "Stopping task $TASK_ARN"
#           aws ecs stop-task --cluster my-cluster --task $TASK_ARN --region $AWS_REGION
#         done

#     - name: Run New ECS Task
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: us-west-1
#       run: |
#         # Run a new task with the latest task definition
#         aws ecs run-task \
#           --cluster my-cluster \
#           --launch-type FARGATE \
#           --network-configuration "awsvpcConfiguration={subnets=[subnet-083f027b4042983e3],securityGroups=[sg-0ba1da8a176fc1e1c],assignPublicIp=ENABLED}" \
#           --task-definition my-task-def \
#           --region $AWS_REGION
name: Deploy Project 1 to ECS
on:
  push:
    branches:
      - branch1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: project1-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./myproject
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Run New ECS Task
        run: |
          aws ecs run-task \
            --cluster my-cluster \
            --task-definition my-task-def \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-083f027b4042983e3],securityGroups=[sg-0ba1da8a176fc1e1c],assignPublicIp=ENABLED}" \
            --region us-west-1
