name: Sync Branches

on:
  schedule:
    - cron: '38 19 * * 1-5' # Runs at 18:55 UTC, Monday to Friday
  workflow_dispatch: # Allows manual trigger

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches to ensure branch1 and branch2 are available

      # Step 2: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Sync `myproject` in branch1 to `myproject1` in branch2
      - name: Sync folder from branch1 to branch2
        run: |
          # Ensure both branches are up-to-date
          git fetch origin

          # Checkout branch1 and pull latest changes
          git checkout branch1
          git pull origin branch1

          # Copy the `myproject` folder to a temporary location
          mkdir -p /tmp/sync
          cp -R myproject/* /tmp/sync/

          # Checkout branch2 and pull latest changes
          git checkout branch2
          git pull origin branch2

          # Sync the `myproject` folder into `myproject1`
          mkdir -p myproject1
          cp -R /tmp/sync/* myproject1/

          # Add, commit, and push changes
          git add myproject1
          git commit -m "Sync myproject from branch1 to myproject1 in branch2" || echo "No changes to commit"
          git push origin branch2
